export const CHANGE_MAIN_BAR_VISIBLE_ACTION = 'CHANGE_MAIN_BAR_VISIBLE_ACTION';

export const SELECT_PLAYING_CITY_ACTION = 'SELECT_PLAYING_CITY_ACTION';

export const FIND_MOVIE_TAB_CHANGE_ACTION = 'FIND_MOVIE_TAB_CHANGE_ACTION';