

export const FIND_MAIN_TAB = 'FIND_MAIN_TAB';

export const FIND_SEARCH_CITY_TAB = 'FIND_SEARCH_CITY_TAB';

export const FIND_SEARCH_MOVIE_TAB = 'FIND_SEARCH_MOVIE_TAB';

export const SEARCH_CITY_OF_PROVINCE_TAB= 'SEARCH_CITY_OF_PROVINCE_TAB';